---
name: test
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt

      - name: run tests
        run: |
          pytest --cov='pureport' --cov-append -v test/
          flake8 pureport test
